on: push
name: Build & Test
env:
  MIX_ENV: test

jobs:
  test:
    runs-on: ubuntu-latest
    name: Ex${{matrix.elixir}}/OTP${{matrix.otp}}
    strategy:
      matrix:
        elixir: ["1.17.3", "1.18.2"]
        otp: ["25.3.2", "26.2.5", "27.2.4"]
    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:5.6.2
        options: >-
          -e "discovery.type=single-node"
          -e "xpack.security.enabled=false"
          -e "path.repo=/tmp"
          --health-cmd "curl -f http://localhost:9200/_cluster/health"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
        ports:
          - 9200:9200
          - 9300:9300
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}
      - run: mix deps.get
      - run: mix compile --warnings-as-errors
      - name: Check formatting
        run: mix format --check-formatted
      - name: Run credo
        run: mix credo --strict
      - name: Run tests
        run: mix test
